### PR TITLE
Added Support for Phone Error Rate(PER)

### PR DESCRIPTION
**Pull request by virmht**

### CODE REVIEW

**Comment by virmht** [comment]
@nshmyrev , as suggested by you, created new PR for PER.

**Comment by nshmyrev** [comment]
This branch has conflicts, please merge in your home branch first.

**Comment by virmht** [comment]
@nshmyrev , resolved conflicts :) , feel free to suggest edits, if any

**Comment by nshmyrev** [comment]
Looks great, how about to remove

```
print('Beginning calculation pronunciation error rate (PER) on test sample.')
```

its a bit meaningless

**Comment by virmht** [comment]
How about making it "print('Beginning calculation phoneme error rate (PER) on test sample.')" ? Or should I just remove it ?

**Comment by nshmyrev** [comment]
Remove it

**Comment by virmht** [comment]
@nshmyrev, Done!

**Comment by nshmyrev** [comment]
Great, thank you!

**Pull request merged**
